### ISSUE TITLE
Create a new branch for testing netty transport native

### ISSUE THREAD

**Issue by mchv** [playframework/prune#3]
@richdougherty I have created a new branch for testing performance of netty native transport socket.
I can't create a new branch in a PR, but if you think it makes sense you can create same branch with my changes:

https://github.com/playframework/prune/compare/apps-master...mchv:apps-master-netty-transport-native

**Comment by gmethvin** [comment]
I know this is old so you may not care at this point, but I would recommend creating a different set of tests for this, the same way we have for netty and akka http.
